# NameItem Configuration
#
# Allow other plugins to listen for item rename events.
# This so plugins that have important names and lores won't break.
useEvents: true
#
# Max number of characters to allow per item name
maxNameChars: 30
#
# Max number of characters to allow per lore line
maxLoreChars: 30
#
# Max lines for lore
maxLoreLines: 5
